-- USER
INSERT INTO USER (agreement_yn, birth, email, gender, account_id, name, password, phone, reg_date)
VALUES ('Y', '19920915', "user1@gmail.com", "male", "user1", "user1", "password1", "01011111111", "2011-08-21 14:11:09");
INSERT INTO USER (agreement_yn, birth, email, gender, account_id, name, password, phone, reg_date)
VALUES ('Y', '19930115', "user2@gmail.com", "female", "user2", "user2", "password2", "01022222222", "2012-03-13 11:07:15");
INSERT INTO USER (agreement_yn, birth, email, gender, account_id, name, password, phone, reg_date)
VALUES ('Y', '19940215', "user3@gmail.com", "male", "user3", "user3", "password3", "01033333333", "2013-05-24 16:25:57");
INSERT INTO USER (agreement_yn, birth, email, gender, account_id, name, password, phone, reg_date)
VALUES ('Y', '19950315', "user4@gmail.com", "female", "user4", "user4", "password4", "01044444444", "2014-02-17 18:37:47");
INSERT INTO USER (agreement_yn, birth, email, gender, account_id, name, password, phone, reg_date)
VALUES ('N', '19960415', "user5@gmail.com", "male", "user5", "user5", "password5", "01055555555", "2015-08-06 15:58:35");
INSERT INTO USER (agreement_yn, birth, email, gender, account_id, name, password, phone, reg_date)
VALUES ('N', '19970515', "user6@gmail.com", "female", "user6", "user6", "password6", "01066666666", "2016-06-05 11:06:03");

-- BANK
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '001', '한국', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '001');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '002', '산업', '002' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '002');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '003', '기업', '003' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '003');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '004', 'ＫB국민', '381' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '004');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '007', '수협은행', '007' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '007');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '008', '수출입은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '008');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '011', 'ＮＨ농협은행', '011' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '011');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '012', '농축협', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '012');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '020', '우리은행', '041' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '020');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '023', 'ＳＣ제일', '361' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '023');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '027', '한국씨티', '027' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '027');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '031', '대구', '361' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '031');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '032', '부산', '361' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '032');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '034', '광주', '034' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '034');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '035', '제주', '035' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '035');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '037', '전북', '037' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '037');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '039', '경남', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '039');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '045', '새마을금고', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '045');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '048', '신협', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '048');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '050', '저축은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '050');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '052', '모간스탠리', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '052');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '054', 'ＨＳＢＣ', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '054');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '055', '도이치은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '055');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '057', '제이피모간체이스', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '057');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '058', '미즈호은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '058');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '059', '엠유에프지은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '059');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '060', 'ＢＯＡ', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '060');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '061', '비엔피파리바', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '061');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '062', '중국공상은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '062');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '063', '중국은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '063');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '064', '산림조합', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '064');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '065', '대화은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '065');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '067', '중국건설은행', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '067');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '071', '우체국', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '071');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '076', '신용보증기금', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '076');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '077', '기술보증기금', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '077');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '081', '하나', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '081');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '088', '신한', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '088');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '089', '케이뱅크', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '089');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '090', '카카오뱅크', '381' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '090');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '092', '토스뱅크', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '092');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '094', '서울보증보험', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '094');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '099', '금융결제원', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '099');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '209', '유안타증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '209');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '218', 'ＫＢ증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '218');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '224', 'ＢＮＫ투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '224');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '225', 'ＩＢＫ투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '225');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '227', '다올투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '227');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '238', '미래에셋증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '238');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '240', '삼성증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '240');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '243', '한국투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '243');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '247', 'ＮＨ투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '247');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '261', '교보증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '261');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '262', '하이투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '262');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '263', '현대차증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '263');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '264', '키움증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '264');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '265', '이베스트투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '264');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '266', 'ＳＫ증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '266');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '267', '대신증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '267');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '268', '메리츠증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '268');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '269', '한화투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '269');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '270', '하나증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '270');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '271', '토스증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '271');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '272', 'ＮＨ선물', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '272');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '278', '신한투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '278');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '279', 'ＤＢ금융투자', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '279');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '280', '유진투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '280');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '287', '메리츠증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '287');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '288', '카카오페이증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '288');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '290', '부국증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '290');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '291', '신영증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '291');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '292', '케이프투자증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '292');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '293', '한국증권금융', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '293');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '294', '한국포스증권', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '294');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '303', '롯데캐피탈', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '303');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '365', '삼성카드', '365' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '365');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '366', '신한카드', '366' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '366');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '367', '현대카드', '367' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '367');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '368', '롯데카드', '368' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '368');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '374', '하나카드', '374' WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '374');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '431', '미래에셋생명', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '431');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '436', '교보생명', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '436');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '438', '신한라이프생명보험', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '438');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '440', '농협생명', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '440');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '441', '삼성화재', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '441');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '442', '현대해상', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '442');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '443', 'ＤＢ손해보험', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '443');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '444', 'ＫＢ손해보험', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '444');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '445', '롯데손해보험', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '445');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '448', '메리츠화재', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '448');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '452', '삼성생명', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '452');
INSERT INTO BANK (BANK_CODE, BANK_NAME, CARD_CODE) SELECT '454', '한화손해보험', null WHERE NOT EXISTS(SELECT 1 FROM BANK WHERE BANK_CODE = '454');

-- ACCOUNT
INSERT INTO account (user_id, bank_id, account_num, available_amt, tran_date, tran_time, inout_type, content, tran_amt, tran_after_amt)
VALUES (1, 4, 1111111111, 3000000, now(), current_time, 'DI', 'CU', 20000, 280000);

INSERT INTO account (user_id, bank_id, account_num, available_amt, tran_date, tran_time, inout_type, content, tran_amt, tran_after_amt)
VALUES (1, 7, 1111117777, 80000000, now(), current_time, 'DI', 'CU', 3000, 8833);

INSERT INTO account (user_id, bank_id, account_num, available_amt, tran_date, tran_time, inout_type, content, tran_amt, tran_after_amt)
VALUES (1, 8, 1111118888, 7000000000, now(), current_time, 'DI', 'CU', 100000, 91919);

INSERT INTO account (user_id, bank_id, account_num, available_amt, tran_date, tran_time, inout_type, content, tran_amt, tran_after_amt)
VALUES (1, 10, 1111999991, 20000, now(), current_time, 'DI', 'CU', 12300, 99132);

INSERT INTO account (user_id, bank_id, account_num, available_amt, tran_date, tran_time, inout_type, content, tran_amt, tran_after_amt)
VALUES (1, 11, 1123411111, 1000, now(), current_time, 'DI', 'CU', 5550, 12340098);

-- CARD
INSERT INTO CARD (card_name, payment_amt, settlement_date, settlement_day, bank_id, user_id)
VALUES ('카드별명1', 10000, '2023-06-01 11:24:43', '05', 1, 1);
INSERT INTO CARD (card_name, payment_amt, settlement_date, settlement_day, bank_id, user_id)
VALUES ('카드별명2', 20000, '2023-05-03 14:25:36', '04', 3, 2);
INSERT INTO CARD (card_name, payment_amt, settlement_date, settlement_day, bank_id, user_id)
VALUES ('카드별명3', 30000, '2023-05-25 12:06:03', '08', 5, 3);
INSERT INTO CARD (card_name, payment_amt, settlement_date, settlement_day, bank_id, user_id)
VALUES ('카드별명4', 40000, '2023-04-13 19:56:31', '10', 7, 4);
INSERT INTO CARD (card_name, payment_amt, settlement_date, settlement_day, bank_id, user_id)
VALUES ('카드별명5', 50000, '2023-05-30 20:45:51', '11', 9, 5);

-- Book
INSERT INTO total_book (user_id, year, month, budget, remain_budget)
VALUES (1, '2023', '06', 3000000, 2345500);

INSERT INTO detail_book (book_id, cost_type, cost, content, memo)
VALUES (1, 'FC', 100000, '주택청약', '주택청약');
INSERT INTO detail_book (book_id, cost_type, cost, content, memo)
VALUES (1, 'FC', 50000, '보험', '현대해상');
INSERT INTO detail_book (book_id, cost_type, cost, content, memo)
VALUES (1, 'FC', 500000, '적금', '절망적금');
INSERT INTO detail_book (book_id, cost_type, cost, content, memo)
VALUES (1, 'VC', 4500, '담배', '편의점');